import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const countries = [
    { id: 1, countryCode: "AF", countryName: "Afghanistan" },
    { id: 2, countryCode: "AX", countryName: "Aland Islands" },
    { id: 3, countryCode: "AL", countryName: "Albania" },
    { id: 4, countryCode: "DZ", countryName: "Algeria" },
    { id: 5, countryCode: "AS", countryName: "American Samoa" },
    { id: 6, countryCode: "AD", countryName: "Andorra" },
    { id: 7, countryCode: "AO", countryName: "Angola" },
    { id: 8, countryCode: "AI", countryName: "Anguilla" },
    { id: 9, countryCode: "AQ", countryName: "Antarctica" },
    { id: 10, countryCode: "AG", countryName: "Antigua and Barbuda" },
    { id: 11, countryCode: "AR", countryName: "Argentina" },
    { id: 12, countryCode: "AM", countryName: "Armenia" },
    { id: 13, countryCode: "AW", countryName: "Aruba" },
    { id: 14, countryCode: "AU", countryName: "Australia" },
    { id: 15, countryCode: "AT", countryName: "Austria" },
    { id: 16, countryCode: "AZ", countryName: "Azerbaijan" },
    { id: 17, countryCode: "ST", countryName: "Sao Tome and Principe" },
    { id: 18, countryCode: "BS", countryName: "Bahamas" },
    { id: 19, countryCode: "BH", countryName: "Bahrain" },
    { id: 20, countryCode: "BD", countryName: "Bangladesh" },
    { id: 21, countryCode: "BB", countryName: "Barbados" },
    { id: 22, countryCode: "BY", countryName: "Belarus" },
    { id: 23, countryCode: "BE", countryName: "Belgium" },
    { id: 24, countryCode: "BZ", countryName: "Belize" },
    { id: 25, countryCode: "BJ", countryName: "Benin" },
    { id: 26, countryCode: "BT", countryName: "Bhutan" },
    { id: 27, countryCode: "BO", countryName: "Bolivia" },
    { id: 28, countryCode: "BA", countryName: "Bosnia and Herzegovina" },
    { id: 29, countryCode: "BW", countryName: "Botswana" },
    { id: 30, countryCode: "BV", countryName: "Bouvet Island" },
    { id: 31, countryCode: "BR", countryName: "Brazil" },
    { id: 32, countryCode: "VG", countryName: "British Virgin Islands" },
    {
      id: 33,
      countryCode: "IO",
      countryName: "British Indian Ocean Territory",
    },
    { id: 34, countryCode: "BN", countryName: "Brunei Darussalam" },
    { id: 35, countryCode: "BG", countryName: "Bulgaria" },
    { id: 36, countryCode: "BF", countryName: "Burkina Faso" },
    { id: 37, countryCode: "BI", countryName: "Burundi" },
    { id: 38, countryCode: "KH", countryName: "Cambodia" },
    { id: 39, countryCode: "CM", countryName: "Cameroon" },
    { id: 40, countryCode: "CA", countryName: "Canada" },
    { id: 41, countryCode: "CV", countryName: "Cape Verde" },
    { id: 42, countryCode: "KY", countryName: "Cayman Islands" },
    { id: 43, countryCode: "CF", countryName: "Central African Republic" },
    { id: 44, countryCode: "TD", countryName: "Chad" },
    { id: 45, countryCode: "CL", countryName: "Chile" },
    { id: 46, countryCode: "CN", countryName: "China" },
    { id: 47, countryCode: "HK", countryName: "Hong Kong, SAR China" },
    { id: 48, countryCode: "CR", countryName: "Costa Rica" },
    { id: 49, countryCode: "MO", countryName: "Macao, SAR China" },
    { id: 50, countryCode: "CX", countryName: "Christmas Island" },
    { id: 51, countryCode: "CC", countryName: "Cocos (Keeling) Islands" },
    { id: 52, countryCode: "CO", countryName: "Colombia" },
    { id: 53, countryCode: "KM", countryName: "Comoros" },
    { id: 54, countryCode: "CD", countryName: "Congo, (Kinshasa)" },
    { id: 55, countryCode: "CK", countryName: "Cook Islands" },
    { id: 56, countryCode: "CI", countryName: "Côte d'Ivoire" },
    { id: 57, countryCode: "HR", countryName: "Croatia" },
    { id: 58, countryCode: "CU", countryName: "Cuba" },
    { id: 59, countryCode: "CY", countryName: "Cyprus" },
    { id: 60, countryCode: "CZ", countryName: "Czech Republic" },
    { id: 61, countryCode: "DK", countryName: "Denmark" },
    { id: 62, countryCode: "DJ", countryName: "Djibouti" },
    { id: 63, countryCode: "DM", countryName: "Dominica" },
    { id: 64, countryCode: "DO", countryName: "Dominican Republic" },
    { id: 65, countryCode: "EC", countryName: "Ecuador" },
    { id: 66, countryCode: "EG", countryName: "Egypt" },
    { id: 67, countryCode: "SV", countryName: "El Salvador" },
    { id: 68, countryCode: "GQ", countryName: "Equatorial Guinea" },
    { id: 69, countryCode: "ER", countryName: "Eritrea" },
    { id: 70, countryCode: "EE", countryName: "Estonia" },
    { id: 71, countryCode: "ET", countryName: "Ethiopia" },
    { id: 72, countryCode: "FK", countryName: "Falkland Islands (Malvinas)" },
    { id: 73, countryCode: "FO", countryName: "Faroe Islands" },
    { id: 74, countryCode: "FJ", countryName: "Fiji" },
    { id: 75, countryCode: "FI", countryName: "Finland" },
    { id: 76, countryCode: "FR", countryName: "France" },
    { id: 77, countryCode: "GF", countryName: "French Guiana" },
    { id: 78, countryCode: "PF", countryName: "French Polynesia" },
    { id: 79, countryCode: "TF", countryName: "French Southern Territories" },
    { id: 80, countryCode: "GA", countryName: "Gabon" },
    { id: 81, countryCode: "GM", countryName: "Gambia" },
    { id: 82, countryCode: "GE", countryName: "Georgia" },
    { id: 83, countryCode: "DE", countryName: "Germany" },
    { id: 84, countryCode: "GH", countryName: "Ghana" },
    { id: 85, countryCode: "GI", countryName: "Gibraltar" },
    { id: 86, countryCode: "GR", countryName: "Greece" },
    { id: 87, countryCode: "GL", countryName: "Greenland" },
    { id: 88, countryCode: "GD", countryName: "Grenada" },
    { id: 89, countryCode: "GP", countryName: "Guadeloupe" },
    { id: 90, countryCode: "GU", countryName: "Guam" },
    { id: 91, countryCode: "GT", countryName: "Guatemala" },
    { id: 92, countryCode: "GG", countryName: "Guernsey" },
    { id: 93, countryCode: "GN", countryName: "Guinea" },
    { id: 94, countryCode: "GW", countryName: "Guinea-Bissau" },
    { id: 95, countryCode: "GY", countryName: "Guyana" },
    { id: 96, countryCode: "HT", countryName: "Haiti" },
    { id: 97, countryCode: "HM", countryName: "Heard and Mcdonald Islands" },
    { id: 98, countryCode: "VA", countryName: "Holy See (Vatican City State)" },
    { id: 99, countryCode: "HN", countryName: "Honduras" },
    { id: 100, countryCode: "HU", countryName: "Hungary" },
    { id: 101, countryCode: "IS", countryName: "Iceland" },
    {
      id: 102,
      countryCode: "FM",
      countryName: "Micronesia, Federated States of",
    },
    { id: 103, countryCode: "RE", countryName: "Réunion" },
    { id: 104, countryCode: "ID", countryName: "Indonesia" },
    { id: 105, countryCode: "IR", countryName: "Iran, Islamic Republic of" },
    { id: 106, countryCode: "IQ", countryName: "Iraq" },
    { id: 107, countryCode: "IE", countryName: "Ireland" },
    { id: 108, countryCode: "IM", countryName: "Isle of Man" },
    { id: 109, countryCode: "IL", countryName: "Israel" },
    { id: 110, countryCode: "IT", countryName: "Italy" },
    { id: 111, countryCode: "JM", countryName: "Jamaica" },
    { id: 112, countryCode: "JP", countryName: "Japan" },
    { id: 113, countryCode: "JE", countryName: "Jersey" },
    { id: 114, countryCode: "JO", countryName: "Jordan" },
    { id: 115, countryCode: "MD", countryName: "Moldova" },
    { id: 116, countryCode: "KZ", countryName: "Kazakhstan" },
    { id: 117, countryCode: "KE", countryName: "Kenya" },
    { id: 118, countryCode: "KI", countryName: "Kiribati" },
    { id: 119, countryCode: "KP", countryName: "Korea (North)" },
    { id: 120, countryCode: "KR", countryName: "Korea (South)" },
    { id: 121, countryCode: "KW", countryName: "Kuwait" },
    { id: 122, countryCode: "KG", countryName: "Kyrgyzstan" },
    { id: 123, countryCode: "LA", countryName: "Lao PDR" },
    { id: 124, countryCode: "LV", countryName: "Latvia" },
    { id: 125, countryCode: "LB", countryName: "Lebanon" },
    { id: 126, countryCode: "LS", countryName: "Lesotho" },
    { id: 127, countryCode: "LR", countryName: "Liberia" },
    { id: 128, countryCode: "LY", countryName: "Libya" },
    { id: 129, countryCode: "LI", countryName: "Liechtenstein" },
    { id: 130, countryCode: "LT", countryName: "Lithuania" },
    { id: 131, countryCode: "LU", countryName: "Luxembourg" },
    { id: 132, countryCode: "MK", countryName: "Macedonia, Republic of" },
    { id: 133, countryCode: "MG", countryName: "Madagascar" },
    { id: 134, countryCode: "MW", countryName: "Malawi" },
    { id: 135, countryCode: "MY", countryName: "Malaysia" },
    { id: 136, countryCode: "MV", countryName: "Maldives" },
    { id: 137, countryCode: "BM", countryName: "Bermuda" },
    { id: 138, countryCode: "ML", countryName: "Mali" },
    { id: 139, countryCode: "MT", countryName: "Malta" },
    { id: 140, countryCode: "MH", countryName: "Marshall Islands" },
    { id: 141, countryCode: "MQ", countryName: "Martinique" },
    { id: 142, countryCode: "MR", countryName: "Mauritania" },
    { id: 143, countryCode: "MU", countryName: "Mauritius" },
    { id: 144, countryCode: "YT", countryName: "Mayotte" },
    { id: 145, countryCode: "MX", countryName: "Mexico" },
    { id: 146, countryCode: "MC", countryName: "Monaco" },
    { id: 147, countryCode: "MN", countryName: "Mongolia" },
    { id: 148, countryCode: "ME", countryName: "Montenegro" },
    { id: 149, countryCode: "MS", countryName: "Montserrat" },
    { id: 150, countryCode: "MA", countryName: "Morocco" },
    { id: 151, countryCode: "MZ", countryName: "Mozambique" },
    { id: 152, countryCode: "MM", countryName: "Myanmar" },
    { id: 153, countryCode: "NA", countryName: "Namibia" },
    { id: 154, countryCode: "NR", countryName: "Nauru" },
    { id: 155, countryCode: "NP", countryName: "Nepal" },
    { id: 156, countryCode: "NL", countryName: "Netherlands" },
    { id: 157, countryCode: "AN", countryName: "Netherlands Antilles" },
    { id: 158, countryCode: "NC", countryName: "New Caledonia" },
    { id: 159, countryCode: "NZ", countryName: "New Zealand" },
    { id: 160, countryCode: "NI", countryName: "Nicaragua" },
    { id: 161, countryCode: "NE", countryName: "Niger" },
    { id: 162, countryCode: "NG", countryName: "Nigeria" },
    { id: 163, countryCode: "NU", countryName: "Niue" },
    { id: 164, countryCode: "NF", countryName: "Norfolk Island" },
    { id: 165, countryCode: "MP", countryName: "Northern Mariana Islands" },
    { id: 166, countryCode: "NO", countryName: "Norway" },
    { id: 167, countryCode: "OM", countryName: "Oman" },
    { id: 168, countryCode: "PK", countryName: "Pakistan" },
    { id: 169, countryCode: "PW", countryName: "Palau" },
    { id: 170, countryCode: "PS", countryName: "Palestinian Territory" },
    { id: 171, countryCode: "PA", countryName: "Panama" },
    { id: 172, countryCode: "PG", countryName: "Papua New Guinea" },
    { id: 173, countryCode: "PY", countryName: "Paraguay" },
    { id: 174, countryCode: "PE", countryName: "Peru" },
    { id: 175, countryCode: "PH", countryName: "Philippines" },
    { id: 176, countryCode: "PN", countryName: "Pitcairn" },
    { id: 177, countryCode: "PT", countryName: "Portugal" },
    { id: 178, countryCode: "PR", countryName: "Puerto Rico" },
    { id: 179, countryCode: "QA", countryName: "Qatar" },
    { id: 180, countryCode: "RO", countryName: "Romania" },
    { id: 181, countryCode: "RU", countryName: "Russian Federation" },
    { id: 182, countryCode: "RW", countryName: "Rwanda" },
    { id: 183, countryCode: "BL", countryName: "Saint-Barthélemy" },
    { id: 184, countryCode: "SH", countryName: "Saint Helena" },
    { id: 185, countryCode: "KN", countryName: "Saint Kitts and Nevis" },
    { id: 186, countryCode: "LC", countryName: "Saint Lucia" },
    { id: 187, countryCode: "MF", countryName: "Saint-Martin (French part)" },
    { id: 188, countryCode: "PM", countryName: "Saint Pierre and Miquelon" },
    { id: 189, countryCode: "VC", countryName: "Saint Vincent and Grenadines" },
    { id: 190, countryCode: "WS", countryName: "Samoa" },
    { id: 191, countryCode: "SM", countryName: "San Marino" },
    { id: 192, countryCode: "SA", countryName: "Saudi Arabia" },
    { id: 193, countryCode: "SN", countryName: "Senegal" },
    { id: 194, countryCode: "RS", countryName: "Serbia" },
    { id: 195, countryCode: "SC", countryName: "Seychelles" },
    { id: 196, countryCode: "SL", countryName: "Sierra Leone" },
    { id: 197, countryCode: "SG", countryName: "Singapore" },
    { id: 198, countryCode: "SK", countryName: "Slovakia" },
    { id: 199, countryCode: "SI", countryName: "Slovenia" },
    { id: 200, countryCode: "SB", countryName: "Solomon Islands" },
    { id: 201, countryCode: "SO", countryName: "Somalia" },
    { id: 202, countryCode: "ZA", countryName: "South Africa" },
    {
      id: 203,
      countryCode: "GS",
      countryName: "South Georgia and the South Sandwich Islands",
    },
    { id: 204, countryCode: "SS", countryName: "South Sudan" },
    { id: 205, countryCode: "ES", countryName: "Spain" },
    { id: 206, countryCode: "LK", countryName: "Sri Lanka" },
    { id: 207, countryCode: "SD", countryName: "Sudan" },
    { id: 208, countryCode: "SR", countryName: "Suriname" },
    {
      id: 209,
      countryCode: "SJ",
      countryName: "Svalbard and Jan Mayen Islands",
    },
    { id: 210, countryCode: "SZ", countryName: "Swaziland" },
    { id: 211, countryCode: "SE", countryName: "Sweden" },
    { id: 212, countryCode: "CH", countryName: "Switzerland" },
    { id: 213, countryCode: "SY", countryName: "Syrian Arab Republic (Syria)" },
    { id: 214, countryCode: "TW", countryName: "Taiwan, Republic of China" },
    { id: 215, countryCode: "TJ", countryName: "Tajikistan" },
    { id: 216, countryCode: "TZ", countryName: "Tanzania, United Republic of" },
    { id: 217, countryCode: "TH", countryName: "Thailand" },
    { id: 218, countryCode: "IN", countryName: "India" },
    { id: 219, countryCode: "CG", countryName: "Congo (Brazzaville)" },
    { id: 220, countryCode: "PL", countryName: "Poland" },
    { id: 221, countryCode: "TL", countryName: "Timor-Leste" },
    { id: 222, countryCode: "TG", countryName: "Togo" },
    { id: 223, countryCode: "TK", countryName: "Tokelau" },
    { id: 224, countryCode: "TO", countryName: "Tonga" },
    { id: 225, countryCode: "TT", countryName: "Trinidad and Tobago" },
    { id: 226, countryCode: "TN", countryName: "Tunisia" },
    { id: 227, countryCode: "TR", countryName: "Turkey" },
    { id: 228, countryCode: "TM", countryName: "Turkmenistan" },
    { id: 229, countryCode: "TC", countryName: "Turks and Caicos Islands" },
    { id: 230, countryCode: "TV", countryName: "Tuvalu" },
    { id: 231, countryCode: "UG", countryName: "Uganda" },
    { id: 232, countryCode: "UA", countryName: "Ukraine" },
    { id: 233, countryCode: "AE", countryName: "United Arab Emirates" },
    { id: 234, countryCode: "GB", countryName: "United Kingdom" },
    { id: 235, countryCode: "US", countryName: "United States of America" },
    { id: 236, countryCode: "UM", countryName: "US Minor Outlying Islands" },
    { id: 237, countryCode: "UY", countryName: "Uruguay" },
    { id: 238, countryCode: "UZ", countryName: "Uzbekistan" },
    { id: 239, countryCode: "VU", countryName: "Vanuatu" },
    {
      id: 240,
      countryCode: "VE",
      countryName: "Venezuela (Bolivarian Republic)",
    },
    { id: 241, countryCode: "VN", countryName: "Viet Nam" },
    { id: 242, countryCode: "VI", countryName: "Virgin Islands, US" },
    { id: 243, countryCode: "WF", countryName: "Wallis and Futuna Islands" },
    { id: 244, countryCode: "EH", countryName: "Western Sahara" },
    { id: 245, countryCode: "YE", countryName: "Yemen" },
    { id: 246, countryCode: "ZM", countryName: "Zambia" },
    { id: 247, countryCode: "ZW", countryName: "Zimbabwe" },
  ];

  for (const country of countries) {
    await prisma.country.upsert({
      where: { countryCode: country.countryCode },
      update: {},
      create: country,
    });
  }

  console.log("Seeded all 247 countries successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
